/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_helldiner_holdon_hook_NetHooksHandler_PipeHandler */

#ifndef _Included_me_helldiner_holdon_hook_NetHooksHandler_PipeHandler
#define _Included_me_helldiner_holdon_hook_NetHooksHandler_PipeHandler
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     me_helldiner_holdon_hook_NetHooksHandler_PipeHandler
	 * Method:    connect
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_me_helldiner_holdon_hook_NetHooksHandler_00024PipeHandler_connect
	(JNIEnv*, jobject);

	/*
	 * Class:     me_helldiner_holdon_hook_NetHooksHandler_PipeHandler
	 * Method:    tick
	 * Signature: (Lme/helldiner/holdon/hook/NetHooksHandler;)V
	 */
	JNIEXPORT void JNICALL Java_me_helldiner_holdon_hook_NetHooksHandler_00024PipeHandler_tick
	(JNIEnv*, jobject, jobject);

	/*
	 * Class:     me_helldiner_holdon_hook_NetHooksHandler_PipeHandler
	 * Method:    sendPacketBytes
	 * Signature: (I)V
	 */
	JNIEXPORT void JNICALL Java_me_helldiner_holdon_hook_NetHooksHandler_00024PipeHandler_sendPacketBytes
	(JNIEnv*, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif