/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_helldiner_holdon_hook_Injector */

#ifndef _Included_me_helldiner_holdon_hook_Injector
#define _Included_me_helldiner_holdon_hook_Injector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_helldiner_holdon_hook_Injector
 * Method:    inject
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_me_helldiner_holdon_hook_Injector_inject
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
